# Generated by Django 5.2.1 on 2025-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0003_historicalsheetimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Item statuses',
            },
        ),
        migrations.AddField(
            model_name='sheetimport',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='sheet_imports', to='ftva_lab_data.itemstatus'),
        ),
    ]
