# Generated by Django 5.2.1 on 2025-06-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0004_itemstatus_sheetimport_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemstatus',
            options={'ordering': ['status'], 'verbose_name_plural': 'Item statuses'},
        ),
    ]
