# Generated by Django 5.2.1 on 2025-06-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0005_alter_itemstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetimport',
            options={'permissions': [('assign_user', 'Can assign user to SheetImport')]},
        ),
    ]
