# Generated by Django 5.2.1 on 2025-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0006_alter_sheetimport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsheetimport',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sheetimport',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
    ]
