# Generated by Django 5.2.1 on 2025-06-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0007_alter_historicalsheetimport_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsheetimport',
            old_name='dml_lto_tape_id',
            new_name='carrier_a',
        ),
        migrations.RenameField(
            model_name='historicalsheetimport',
            old_name='arsc_lto_tape_id',
            new_name='carrier_b',
        ),
        migrations.RenameField(
            model_name='sheetimport',
            old_name='dml_lto_tape_id',
            new_name='carrier_a',
        ),
        migrations.RenameField(
            model_name='sheetimport',
            old_name='arsc_lto_tape_id',
            new_name='carrier_b',
        ),
        migrations.AddField(
            model_name='historicalsheetimport',
            name='carrier_a_location',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='historicalsheetimport',
            name='carrier_b_location',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='sheetimport',
            name='carrier_a_location',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='sheetimport',
            name='carrier_b_location',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
