# Generated by Django 5.2.2 on 2025-07-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0008_rename_dml_lto_tape_id_historicalsheetimport_carrier_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsheetimport',
            name='date_of_ingest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetimport',
            name='date_of_ingest',
            field=models.DateField(blank=True, null=True),
        ),
    ]
