# Generated by Django 5.2.2 on 2025-08-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0009_historicalsheetimport_date_of_ingest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsheetimport',
            name='file_type',
            field=models.CharField(blank=True, choices=[('MOV', 'MOV'), ('DPX', 'DPX'), ('WAV', 'WAV'), ('DCP', 'DCP'), ('MP4', 'MP4'), ('AVI', 'AVI'), ('MKV', 'MKV'), ('FLV', 'FLV'), ('F4V', 'F4V'), ('MPEG-1', 'MPEG-1'), ('MPEG-2', 'MPEG-2'), ('M4V', 'M4V'), ('WMV', 'WMV'), ('MP3', 'MP3'), ('WEBM', 'WEBM'), ('VOB', 'VOB'), ('OGG', 'OGG'), ('DIRAC', 'DIRAC'), ('GIFV', 'GIFV'), ('MNG', 'MNG'), ('MTS', 'MTS'), ('M2TS', 'M2TS'), ('TS', 'TS'), ('YUV', 'YUV'), ('RM', 'RM'), ('RMVB', 'RMVB'), ('VIV', 'VIV'), ('ASF', 'ASF'), ('AMV', 'AMV'), ('SVI', 'SVI'), ('MXF', 'MXF'), ('ROQ', 'ROQ'), ('NSV', 'NSV'), ('3GPP', '3GPP'), ('3GPP2', '3GPP2')], max_length=10),
        ),
        migrations.AddField(
            model_name='sheetimport',
            name='file_type',
            field=models.CharField(blank=True, choices=[('MOV', 'MOV'), ('DPX', 'DPX'), ('WAV', 'WAV'), ('DCP', 'DCP'), ('MP4', 'MP4'), ('AVI', 'AVI'), ('MKV', 'MKV'), ('FLV', 'FLV'), ('F4V', 'F4V'), ('MPEG-1', 'MPEG-1'), ('MPEG-2', 'MPEG-2'), ('M4V', 'M4V'), ('WMV', 'WMV'), ('MP3', 'MP3'), ('WEBM', 'WEBM'), ('VOB', 'VOB'), ('OGG', 'OGG'), ('DIRAC', 'DIRAC'), ('GIFV', 'GIFV'), ('MNG', 'MNG'), ('MTS', 'MTS'), ('M2TS', 'M2TS'), ('TS', 'TS'), ('YUV', 'YUV'), ('RM', 'RM'), ('RMVB', 'RMVB'), ('VIV', 'VIV'), ('ASF', 'ASF'), ('AMV', 'AMV'), ('SVI', 'SVI'), ('MXF', 'MXF'), ('ROQ', 'ROQ'), ('NSV', 'NSV'), ('3GPP', '3GPP'), ('3GPP2', '3GPP2')], max_length=10),
        ),
    ]
