# Generated by Django 5.2.2 on 2025-08-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0011_historicalsheetimport_uuid_sheetimport_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsheetimport',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Intermediate', 'Intermediate'), ('Final Version', 'Final Version'), ('Derivative', 'Derivative'), ('Exhibition Copy', 'Exhibition Copy'), ('Access', 'Access'), ('Proxy', 'Proxy'), ('Unknown', 'Unknown')], max_length=25),
        ),
        migrations.AddField(
            model_name='sheetimport',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Intermediate', 'Intermediate'), ('Final Version', 'Final Version'), ('Derivative', 'Derivative'), ('Exhibition Copy', 'Exhibition Copy'), ('Access', 'Access'), ('Proxy', 'Proxy'), ('Unknown', 'Unknown')], max_length=25),
        ),
    ]
