# Generated by Django 5.2.2 on 2025-08-22 22:44

# Migration 0011 introduced a non-unique UUID field to the SheetImport model.
# This migration removes the non-unique UUID field, then adds a truly unique UUID field,
# following the general guidance in the Django documentation, though combining it into a single migration.
# See @https://docs.djangoproject.com/en/5.2/howto/writing-migrations/#migrations-that-add-unique-fields

from django.db import migrations, models
import uuid

def generate_uuid_for_existing_records(apps, schema_editor):
    """Generate UUIDs for all existing records.

    :param apps: Django apps registry.
    :param schema_editor: Django schema editor.
    """
    # Get the model and database alias using the correct context.
    # See @https://docs.djangoproject.com/en/5.2/ref/migration-operations/#runpython for more info.
    SheetImport = apps.get_model("ftva_lab_data", "SheetImport")
    db_alias = schema_editor.connection.alias

    sheet_import_records = SheetImport.objects.using(db_alias).all()
    for record in sheet_import_records:
        record.uuid = uuid.uuid4()

    SheetImport.objects.using(db_alias).bulk_update(
        sheet_import_records, ["uuid"], batch_size=1000
    )

class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0013_historicalsheetimport_no_ingest_reason_and_more'),
    ]

    operations = [
        # Remove the non-unique UUID field
        migrations.RemoveField(
            model_name='sheetimport',
            name='uuid',
        ),
        # Add a new, intermediate UUID field that can be null
        migrations.AddField(
            model_name="sheetimport",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        # Set true UUIDs for existing records, using the custom migration operation
        migrations.RunPython(generate_uuid_for_existing_records, migrations.RunPython.noop),
        # Now make the UUID field non-nullable, unique, and non-editable
        migrations.AlterField(
            model_name="sheetimport",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=False, unique=True, editable=False),
        ),
    ]
