# Generated by Django 5.2.2 on 2025-08-27 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ftva_lab_data", "0014_remove_add_alter_sheetimport_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsheetimport",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[("video", "video"), ("audio", "audio"), ("image", "image")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sheetimport",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[("video", "video"), ("audio", "audio"), ("image", "image")],
                max_length=10,
            ),
        ),
    ]
