# Generated by Django 5.2.2 on 2025-08-27 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0015_historicalsheetimport_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsheetimport',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
