# Generated by Django 5.2.2 on 2025-09-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0016_alter_historicalsheetimport_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsheetimport',
            name='no_ingest_reason',
            field=models.CharField(blank=True, choices=[('Unnecessary Deliverable Export', 'Unnecessary Deliverable Export'), ('Deposit/No Docs', 'Deposit/No Docs'), ('Gift/No Docs', 'Gift/No Docs'), ('Other Permission/No Docs', 'Other Permission/No Docs'), ('Docs OK - Superseded by another version', 'Docs OK - Superseded by another version'), ('Docs OK/Other - See Notes', 'Docs OK/Other - See Notes'), ('File for Programming', 'File for Programming')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sheetimport',
            name='no_ingest_reason',
            field=models.CharField(blank=True, choices=[('Unnecessary Deliverable Export', 'Unnecessary Deliverable Export'), ('Deposit/No Docs', 'Deposit/No Docs'), ('Gift/No Docs', 'Gift/No Docs'), ('Other Permission/No Docs', 'Other Permission/No Docs'), ('Docs OK - Superseded by another version', 'Docs OK - Superseded by another version'), ('Docs OK/Other - See Notes', 'Docs OK/Other - See Notes'), ('File for Programming', 'File for Programming')], max_length=50),
        ),
    ]
