# Generated by Django 5.2.2 on 2025-09-12 20:52

from django.db import migrations, models

def create_dropdown_model_instances(apps, schema_editor):
    """Create instances of the new dropdown models
    for each existing choice value on the corresponding `SheetImport` fields,
    so they can be mapped to new foreign key fields on `SheetImport`.

    :param apps: Django apps registry.
    :param schema_editor: Django schema editor.
    """
    SheetImport = apps.get_model("ftva_lab_data", "SheetImport")
    AssetType = apps.get_model("ftva_lab_data", "AssetType")
    FileType = apps.get_model("ftva_lab_data", "FileType")
    MediaType = apps.get_model("ftva_lab_data", "MediaType")
    NoIngestReason = apps.get_model("ftva_lab_data", "NoIngestReason")

    asset_type_choices = SheetImport._meta.get_field("asset_type").choices
    file_type_choices = SheetImport._meta.get_field("file_type").choices
    media_type_choices = SheetImport._meta.get_field("media_type").choices
    no_ingest_reason_choices = SheetImport._meta.get_field("no_ingest_reason").choices

    # Create an AssetType object for each choice in the `asset_type` field on `SheetImport`...
    for value, _ in asset_type_choices:
        AssetType.objects.create(asset_type=value)
    # ...and so on for the other new models.    
    for value, _ in file_type_choices:
        FileType.objects.create(file_type=value)
    for value, _ in media_type_choices:
        MediaType.objects.create(media_type=value)
    for value, _ in no_ingest_reason_choices:
        NoIngestReason.objects.create(no_ingest_reason=value)

class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0017_alter_historicalsheetimport_no_ingest_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(unique=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Asset types',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(unique=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'File types',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(unique=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Media types',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='NoIngestReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ingest_reason', models.CharField(unique=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'No ingest reasons',
                'ordering': ['pk'],
            },
        ),
        # Create instances of the new dropdown models for each of the choices in the existing `CharField` fields on `SheetImport`
        migrations.RunPython(create_dropdown_model_instances, migrations.RunPython.noop),
    ]
