# Generated by Django 5.2.2 on 2025-09-12 20:59

import django.db.models.deletion
from django.db import migrations, models


def migrate_data_to_foreign_key_fields(apps, schema_editor):
    """Migrate data to the new foreign key fields on `SheetImport`.

    :param apps: Django apps registry.
    :param schema_editor: Django schema editor.
    """
    SheetImport = apps.get_model("ftva_lab_data", "SheetImport")
    AssetType = apps.get_model("ftva_lab_data", "AssetType")
    FileType = apps.get_model("ftva_lab_data", "FileType")
    MediaType = apps.get_model("ftva_lab_data", "MediaType")
    NoIngestReason = apps.get_model("ftva_lab_data", "NoIngestReason")

    records_to_update = []
    # For all records, set the foreign key relationship to the new dropdown models,
    # if the current `CharField` value is not empty (i.e. not '')
    for record in SheetImport.objects.all():
        if record.asset_type:
            record.asset_type_temp = AssetType.objects.get(asset_type=record.asset_type)
        if record.file_type:
            record.file_type_temp = FileType.objects.get(file_type=record.file_type)
        if record.media_type:
            record.media_type_temp = MediaType.objects.get(media_type=record.media_type)
        if record.no_ingest_reason:
            record.no_ingest_reason_temp = NoIngestReason.objects.get(
            no_ingest_reason=record.no_ingest_reason
        )
        records_to_update.append(record)

    SheetImport.objects.bulk_update(
        records_to_update,
        [
            "asset_type_temp",
            "file_type_temp",
            "media_type_temp",
            "no_ingest_reason_temp",
        ],
        batch_size=1000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ftva_lab_data", "0018_assettype_filetype_mediatype_noingestreason"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsheetimport",
            name="asset_type_temp",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ftva_lab_data.assettype",
            ),
        ),
        migrations.AddField(
            model_name="historicalsheetimport",
            name="file_type_temp",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ftva_lab_data.filetype",
            ),
        ),
        migrations.AddField(
            model_name="historicalsheetimport",
            name="media_type_temp",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ftva_lab_data.mediatype",
            ),
        ),
        migrations.AddField(
            model_name="historicalsheetimport",
            name="no_ingest_reason_temp",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ftva_lab_data.noingestreason",
            ),
        ),
        migrations.AddField(
            model_name="sheetimport",
            name="asset_type_temp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sheet_imports",
                to="ftva_lab_data.assettype",
            ),
        ),
        migrations.AddField(
            model_name="sheetimport",
            name="file_type_temp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sheet_imports",
                to="ftva_lab_data.filetype",
            ),
        ),
        migrations.AddField(
            model_name="sheetimport",
            name="media_type_temp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sheet_imports",
                to="ftva_lab_data.mediatype",
            ),
        ),
        migrations.AddField(
            model_name="sheetimport",
            name="no_ingest_reason_temp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sheet_imports",
                to="ftva_lab_data.noingestreason",
            ),
        ),
        # Migrate data from the existing `CharField` fields on `SheetImport` to the new `ForeignKey` fields
        migrations.RunPython(migrate_data_to_foreign_key_fields, migrations.RunPython.noop),
    ]
