# Generated by Django 5.2.2 on 2025-09-16 23:07

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0019_migrate_data_to_foreign_key_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsheetimport',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='historicalsheetimport',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='historicalsheetimport',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='historicalsheetimport',
            name='no_ingest_reason',
        ),
        migrations.RemoveField(
            model_name='sheetimport',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='sheetimport',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='sheetimport',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='sheetimport',
            name='no_ingest_reason',
        ),
        migrations.RenameField(
            model_name='sheetimport',
            old_name='asset_type_temp',
            new_name='asset_type',
        ),
        migrations.RenameField(
            model_name='sheetimport',
            old_name='file_type_temp',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='sheetimport',
            old_name='media_type_temp',
            new_name='media_type',
        ),
        migrations.RenameField(
            model_name='sheetimport',
            old_name='no_ingest_reason_temp',
            new_name='no_ingest_reason',
        ),
        migrations.RenameField(
            model_name='historicalsheetimport',
            old_name='asset_type_temp',
            new_name='asset_type',
        ),
        migrations.RenameField(
            model_name='historicalsheetimport',
            old_name='file_type_temp',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='historicalsheetimport',
            old_name='media_type_temp',
            new_name='media_type',
        ),
        migrations.RenameField(
            model_name='historicalsheetimport',
            old_name='no_ingest_reason_temp',
            new_name='no_ingest_reason',
        ),
    ]
