# Generated by Django 5.2.6 on 2025-10-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0020_remove_historicalsheetimport_asset_type_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_class', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Audio classes',
                'ordering': ['audio_class'],
            },
        ),
        migrations.AddField(
            model_name='historicalsheetimport',
            name='audio_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ftva_lab_data.audioclass'),
        ),
        migrations.AddField(
            model_name='sheetimport',
            name='audio_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_imports', to='ftva_lab_data.audioclass'),
        ),
    ]
