# Generated by Django 5.2.6 on 2025-12-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ftva_lab_data", "0021_audioclass_historicalsheetimport_audio_class_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sheetimport",
            options={
                "permissions": [
                    ("assign_user", "Can assign user to SheetImport"),
                    ("batch_update", "Can apply batch updates to SheetImport"),
                ]
            },
        ),
    ]
