# Generated by Django 5.2.10 on 2026-02-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ftva_lab_data", "0022_sheetimport_create_batch_update_perm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="ftva_lab_data.sheetimport",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="ftva_lab_data.sheetimport",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sheetimport",
            name="relationships",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to",
                through="ftva_lab_data.Relationship",
                to="ftva_lab_data.sheetimport",
            ),
        ),
        migrations.CreateModel(
            name="RelationshipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "inverse",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inverse_of",
                        to="ftva_lab_data.relationshiptype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="relationship",
            name="relationship_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="ftva_lab_data.relationshiptype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="relationship",
            unique_together={("source", "target", "relationship_type")},
        ),
    ]
