# Generated by Django 5.2.10 on 2026-03-10 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ftva_lab_data", "0022_sheetimport_create_batch_update_perm"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationshipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        help_text=(
                            "Main label (i.e. predicate) for the relationship. "
                            "E.g. `ObjectA hasPart ObjectB`."
                        ),
                    ),
                ),
                (
                    "reverse_type",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        help_text=(
                            "Reverse label for the relationship. "
                            "E.g. `ObjectB isPartOf ObjectA`."
                        ),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="ftva_lab_data.sheetimport",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="ftva_lab_data.sheetimport",
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="ftva_lab_data.relationshiptype",
                        help_text=(
                            "Type of relationship between the source and target objects, "
                            "given as a pair of semantically inverse labels. "
                            "E.g. 'hasPart/isPartOf'."
                        ),
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "target", "relationship_type")},
            },
        ),
    ]
