# Generated by Django 5.2.10 on 2026-03-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftva_lab_data', '0023_relationshiptype_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsheetimport',
            name='batch_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sheetimport',
            name='batch_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
