# Generated by Django 5.2.10 on 2026-03-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ftva_lab_data", "0024_historicalsheetimport_batch_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relationship",
            options={
                "permissions": [("manage_relationships", "Can manage relationships")]
            },
        ),
    ]
