apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ftva-lab-data.fullname" . }}-configmap
  namespace: ftva-lab-data{{ .Values.django.env.run_env }}
  labels:
    {{- include "ftva-lab-data.labels" . | nindent 4 }}
data:
  DJANGO_RUN_ENV: {{ .Values.django.env.run_env }}
  DJANGO_DEBUG: {{ .Values.django.env.debug | quote }}
  DJANGO_ALLOWED_HOSTS: {{ range .Values.django.env.allowed_hosts }}{{ . | quote }}{{ end }}
  DJANGO_CSRF_TRUSTED_ORIGINS: {{ range .Values.django.env.csrf_trusted_origins }}{{ . | quote }}{{ end }}
  DJANGO_LOG_LEVEL: {{ .Values.django.env.log_level }}
  DJANGO_DB_BACKEND: {{ .Values.django.env.db_backend }}
  DJANGO_DB_NAME: {{ .Values.django.env.db_name }}
  DJANGO_DB_USER: {{ .Values.django.env.db_user }}
  DJANGO_DB_HOST: {{ .Values.django.env.db_host }}
  DJANGO_DB_PORT: {{ .Values.django.env.db_port | quote }}
  DJANGO_EMAIL_SMTP_SERVER: {{ .Values.django.env.email_smtp_server }}
  DJANGO_EMAIL_SMTP_PORT: {{ .Values.django.env.email_smtp_port | quote }}
  DJANGO_EMAIL_FROM_ADDRESS: {{ .Values.django.env.email_from_address }}
  DJANGO_EMAIL_PASSWORD: {{ .Values.django.env.email_password | default "" | quote }}
  
