{{ if not .Values.django.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ftva-lab-data.fullname" . }}-secrets
  namespace: ftva-lab-data{{ .Values.django.env.run_env }}
  labels:
{{ include "ftva-lab-data.fullname" . | indent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ randAlphaNum 20 | b64enc | quote }}
  DJANGO_DB_PASSWORD: {{ .Values.django.env.db_password | b64enc | quote }}
  FILEMAKER_PASSWORD: {{ .Values.django.env.filemaker_password | b64enc | quote }}
  FILEMAKER_USER: {{ .Values.django.env.filemaker_user | b64enc | quote }}
  AIRTABLE_APP_ID: {{ .Values.django.env.airtable_app_id | b64enc | quote }}
  AIRTABLE_SHARE_ID: {{ .Values.django.env.airtable_share_id | b64enc | quote }}
{{ end }}
